english/urls.py
from django.contrib import admin
from django.urls import path, include
from englishman.views import EnglishView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', EnglishView.as_view(), name='api'),
    path('', include('englishman.urls')),
]

englishman/urls.py
from django.urls import path 

from . import views

urlpatterns = [
    path('', views.common_words_view, name='common'),
    path('about-me/', views.about, name='about'),
    path('api-document/', views.api_doc, name='apidoc'),
]

englishman/models.py
from django.db import models

# Create your models here.

englishman/forms.py
from django import forms

class CommonWordsForm(forms.Form):
    text = forms.CharField(
        widget=forms.Textarea()
    )
    num = forms.IntegerField()

englishman/views.py
from django.http import HttpResponse
from django.shortcuts import render
from rest_framework import generics
from rest_framework import status
from django.contrib.auth.models import User
from .serializers import EnglishSerializer
from rest_framework.exceptions import APIException
import time
import spacy
nlp = spacy.load('en_core_web_sm')
from bs4 import BeautifulSoup
from collections import Counter

from .forms import CommonWordsForm

def five_noun(html_text, num=7):
    soup = BeautifulSoup(html_text, 'html.parser')
    text = str(soup.get_text().replace('\xa0', ''))
    doc = nlp(text)
    # all tokens that arent stop words or punctuations
    words = [(token.lemma_).lower()
            for token in doc
            if not token.is_stop and not token.is_punct]

    # noun tokens that arent stop words or punctuations
    # nouns = [(token.lemma_).lower()
    #         for token in doc
    #         if (not token.is_stop and
    #             not token.is_punct and
    #             token.pos_ == "NOUN")]

    # five most common tokens
    word_freq = Counter(words)
    common_words = word_freq.most_common(num)

    # # five most common noun tokens
    # noun_freq = Counter(nouns)
    # common_nouns = noun_freq.most_common(num)
    return common_words


class Success(APIException):
    status_code = status.HTTP_202_ACCEPTED
    default_detail = 'Success .'
    default_code = 'success'


class EnglishView(generics.RetrieveUpdateDestroyAPIView):
    queryset = User.objects.all()
    serializer_class = EnglishSerializer



    def update(self, request, *args, **kwargs):
        text = request.data['text']
        start_time = time.time()
        k2 = five_noun(html_text=text, num=7)
        endtime = time.time() - start_time
        data = {'words': k2, 'time': endtime}
        raise Success(data)
    

    def get(self, request, *args, **kwargs):
        raise Success('a')

    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def patch(self, request, *args, **kwargs):
        return self.partial_update(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)


def common_words_view(request):
    if request.method == 'POST':
        form = CommonWordsForm(
            request.POST
        )
        if form.is_valid():
            cd = form.cleaned_data
            text = cd['text']
            num = cd['num']
            words = five_noun(text, num=num)
            return render(
                request,
                'englishman/index.html', {
                    'words': [word[0] for word in words]
                }
            )
    else:
        form = CommonWordsForm(request.POST)
    # print(text)
    return render(
        request,
        'englishman/index.html', {
            'form': form
        }
    )





def about(request):
    return render(
        request,
        'englishman/about.html', {
            
        }
    )


def api_doc(request):
    html = '<p>Some long string text You need summary for</p>'
    return render(
        request,
        'englishman/apidoc.html', {
            'html': html,
        }
    )

englishman/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MostUsed words by VIZVASRJ</title>
    {% block c %}		{% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
        {% block style %} {% endblock %}

    </style>

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container">
            <a class="navbar-brand" href="/">Most used words</a>
            <button class="navbar-toggler d-lg-none" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavId" aria-controls="collapsibleNavId"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavId">
                <ul class="navbar-nav me-auto mt-2 mt-lg-0">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'about' %}">About Me<span class="visually-hidden">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'api' %}">API</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'apidoc' %}">API documentation</a>
                    </li>
                </ul>
            </div>
      </div>
    </nav>
    <div class="container">
        {% block content %}	
        
        {% endblock %}

    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

englishman/templates/englishman/about.html
{% extends 'base.html' %}

{% block content %}	
<div class="row p-2">
    <div class="col-lg-2">
        <div><h3>
            I am <i>Saurav Raj</i> as <strong>Vizvasrj</strong>
        </h3></div>
    </div>
    <div class="col-lg-8">
        <ul>
            <li>I have Used <a href="https://www.crummy.com/software/BeautifulSoup/bs4/doc/">BeautifulSoup</a> in this.</li>
            <li>And <a href="spacy.io/">Spacy</a> nlp libirary</li>
            <li>And <a href="https://www.django-rest-framework.org/">Django restApi</a></li>
        </ul>
    </div>
    <div class="col-lg-2"></div>
</div>

{% endblock %}


{% block c %}	
<link rel="canonical" href="https://pypi.org/project/sumy/" />
{% endblock %}

englishman/templates/englishman/apidoc.html
{% extends 'base.html' %}

{% block content %}	
<div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6">

        <h1>API document</h1>
        <p>
            using python requests is my best practice
            <pre>import requests</pre>
            <pre>url = 'https://nlpen.herokuapp.com/api/'</pre>
            <pre>string_html = '''{{html}}'''</pre>
            <pre>r = requests.patch(url, data={'text': string_html, 'num': 7})</pre>
            <pre>words = r.json()['words']</pre>
            <p><code>text</code> is String</p>
            <p><code>num</code> is Int</p>
        </p>
    </div>
    <div class="col-lg-3"></div>
</div>
{% endblock %}

{% block style %}	
pre {
    background: #aaaaaa50;
    padding: 5px;

}
code {
    background: #aaaaaa50
}

{% endblock %}

englishman/templates/englishman/index.html
{% extends 'base.html' %}
{% block content %}

<div class="row">
<div class="col-lg-3"></div>

<div class="col-lg-6">
    {% if form %}
    <form method="POST" class="p-2">
        <div class="p">
            <p><i>This is Good for getting most used keywords from any html</i></p>
            <p><i>I have used this in <a href="https://vizvasrj.com">vizvasrj.com</a></i></p>
            <p><i><bold>Note</bold> it best works with english texts. beacuse of spacy english module</i></p>
        </div>
        <div class="border">
            <label class="p-2" for="text">Enter HTML</label>
                <div class="grow-wrap p-2">
                    <textarea class="p-2" name="text" rows="10" id="id_text" onInput="this.parentNode.dataset.replicatedValue = this.value"></textarea>
                </div>
        </div>
        <div class="border">
            <label class="p-2" for="num">Enter positive number only</label>
            <div class="p-2">
                <input style="width: 100%;" class="p-2" type="number" name="num" required="" id="id_num" min="1" max="5">
            </div>
        </div>
        {% csrf_token %}
    
        
    
        <input class="p-2 btn btn-primary" style="width: 100%;" type="submit" value="Submit">
        
    </form>
    {% endif %}
    
    
    {% for word in words %}
        <div class=" p-1 {% cycle 'bg-primary' 'bg-danger' %}">{{word}}</div>
    {% endfor %}
</div>
<div class="col-lg-3"></div>
    
</div>
{% endblock %}


{% block style %}	
.grow-wrap {
    /* easy way to plop the elements on top of each other and have them both sized based on the tallest one's height */
    display: grid;
  }
  
  .grow-wrap::after {
    /* Note the weird space! Needed to preventy jumpy behavior */
    content: attr(data-replicated-value) " ";
    /* This is how textarea text behaves */
    white-space: pre-wrap;
    /* Hidden from view, clicks, and screen readers */
    visibility: hidden;
  }
  
  .grow-wrap>textarea {
    /* You could leave this, but after a user resizes, then it ruins the auto sizing */
    resize: none;
    /* Firefox shows scrollbar on growth, you can hide like this. */
    overflow: hidden;
  }
  
  .grow-wrap>textarea,
  .grow-wrap::after {
    /* Identical styling required!! */
    border: 1px solid black;
    padding: 0.5rem;
    font: inherit;
    /* Place on top of each other */
    grid-area: 1 / 1 / 2 / 2;
  }
  
.p{
    line-height: 3px;
}

{% endblock %}